# Generated by Django 2.2.4 on 2020-08-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
