# Generated by Django 2.2.4 on 2020-08-13 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninjas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
