# Generated by Django 2.2.4 on 2020-08-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_two_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_wish',
            field=models.IntegerField(default=0),
        ),
    ]
