# Generated by Django 2.2.4 on 2020-08-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_two_app', '0002_auto_20200821_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='liked_wish',
            field=models.ManyToManyField(related_name='likes_wish', to='exam_two_app.User'),
        ),
    ]
