# Generated by Django 2.2.4 on 2020-08-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_two_app', '0003_wish_liked_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='liked_wish',
        ),
        migrations.AddField(
            model_name='user',
            name='wishes_liked',
            field=models.ManyToManyField(related_name='users_who_liked', to='exam_two_app.Wish'),
        ),
    ]
